# Generated by Django 5.2.4 on 2026-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee_currency',
            field=models.CharField(choices=[('USD', 'Dollar (USD)'), ('INR', 'Rupee (INR)')], default='USD', max_length=3),
        ),
    ]
